# Generated by Django 4.2 on 2025-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="outfit_images/"),
        ),
    ]
