# Generated by Django 4.2 on 2025-04-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_outfit_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="clothingitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="clothing_items/"),
        ),
    ]
