# Generated by Django 5.1.6 on 2025-04-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_clothingitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='item_type',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(choices=[('formal', 'Formal'), ('bussiness', 'Bussiness'), ('business casual', 'Business Casual'), ('smart casual', 'Smart Casual'), ('casual', 'Casual')], max_length=50),
        ),
    ]
